### PR TITLE
Adds Goblin Warboss

### PR DESCRIPTION
**Pull request by Striketester**
Goblin Warboss for more lore has a new title in code and chainmail to show DA TRUE LEADA!, Instead of basic ass "leader" its now the WARBOSS, and to show this rank the boss has chainmail.

### CODE REVIEW

**Comment by DeadliestDesire** [comment]
Warboss says: "What the hell do you boys think that this here is, fucking Fairyland? Pulling on your wee-wees like a pack of fucking fruits?"


image

**Comment by BartDrown** [comment]
Still doesn't change anything cause it wouldn't be spawned even by admin.
Add to admin panel option to include goblin "warboss" into spawned admins, preferably that if goblins raid is bigger than idk 6 or so goblins, it includes "warboss".
Also, quite not sure about naming, warboss seems pretty gay and out of a Dwarf Fotress itself, more like Warhammer thing.
I suggest Warlord, i think it describes his function better and I think it does fit setting itself, but it's up for discussion.

**Comment by BartDrown** [comment]
Okay, nevermind about spawning, it is done already.
Allthough Max also would rather have Warlord cause it sounds better and fits

**Comment by Striketester** [comment]
Warboss is a bring back too 40k that's why I chose it.

**Comment by daxsc** [comment]
I don't think this is a good idea. Giving chainmail to a goblin leader will just give dwarves free chainmail each raid considering almost every single raid fails.

**Comment by Striketester** [comment]
> I don't think this is a good idea. Giving chainmail to a goblin leader will just give dwarves free chainmail each raid considering almost every single raid fails.

If I just leave it to a change of name can you pass it?

**Pull request closed without merging**
